name: Generate Snake

on:
  # Her 6 saatte bir otomatik olarak çalışır
  schedule:
    - cron: "0 */6 * * *"
  
  # İstendiğinde manuel olarak çalıştırılabilir
  workflow_dispatch:

jobs:
  build:
    # İş akışının çalışacağı runner tipi
    runs-on: ubuntu-latest

    steps:
      # Depoyu checkout yapar
      - uses: actions/checkout@v2

      # Yılan görselleştirmesini oluşturur
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: suhandusunceli
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Git durumunu kontrol eder (isteğe bağlı)
      - run: git status

      # Değişiklikleri output branch'ına gönderir
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true

      # GitHub Pages'e dağıtır
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
